apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: emanuelmassafera/imersao-fc6-golang
        envFrom:
          - secretRef:
              name: golang-secret
