apiVersion: v1
kind: Secret
metadata:
  name: golang-secret
type: Opaque
data:
  MAIL_HOST: c210cC5tYWlsdHJhcC5pbw==
  MAIL_PORT: MjUyNQ==
  MAIL_USER: YTk4YWFhMGMxMTA0YWI=
  MAIL_PASSWORD: ZWVmY2VjNzk1NzNhMGQ=
  MAIL_FROM: ZnVsbEBjeWNsZS5jb20=
  BOOTSTRAP_SERVERS: cGtjLTZvanYyLnVzLXdlc3Q0LmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
  SECURITY_PROTOCOL: U0FTTF9TU0w=
  SASL_MECHANISMS: UExBSU4=
  SASL_USERNAME: UEE1VjJVUlVVTUcyRUFaWA==
  SASL_PASSWORD: aTZkaXdKb3FWcXFYOUd0UXpRS0VHN24xbjZFTTJKMDREd1lXYVNFT3BHcGh4OGE2d0c4NUJBT2c5RVVNUlpiYw==